language: php

php:
    - '5.6'
    - '7.0'
    - '7.1'
    - '7.2'
    - '7.3'

cache:
  directories:
    - $HOME/.composer/cache

services:
    - mysql

before_script:
    - composer self-update
    - composer install --no-ansi
    - mysql -e 'create database dsql_test;'
    - mkdir -p build/logs

script:
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.2" ]]; then CM=""; NC=""; else CM=""; NC="--no-coverage"; fi
    - $CM ./vendor/bin/phpunit --configuration phpunit.xml $NC

after_script:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.2" ]]; then
      echo "We now have these coverage files:";
      ls -l build/logs;
      echo "Sending codeclimate report:";
      vendor/bin/test-reporter --coverage-report build/logs/clover.xml;
      echo "Sending codecov report:";
      TRAVIS_CMD="" bash <(curl -s https://codecov.io/bash) -f build/logs/clover.xml;
    fi
